version: '3.7'

services:
  
    db:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      networks:
        - my-network
      environment:
        - POSTGRES_USER=fastprepusa
        - POSTGRES_PASSWORD=fastprepusa
        - POSTGRES_DB=fastprepusa

    backend:
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./docker/backend/Dockerfile
      volumes:
          - static_volume:/app/backend/staticfiles
          - media_volume:/app/backend/media
      entrypoint: /app/docker/backend/wsgi-entrypoint.sh
      networks:
        - my-network
      depends_on:
        - db

    nginx:
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
      ports:
        - 80:80
      volumes:
        - ./docker/nginx/:/etc/nginx/conf.d
        - static_volume:/app/backend/staticfiles
        - media_volume:/app/backend/media
      networks:
        - my-network
      depends_on:
        - backend

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  my-network:
